In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("L:\\Workspace\\Resources\\UPDATED_NLP_COURSE\\TextFiles\\moviereviews.tsv", sep= '\t')

In [6]:
df.head()

  label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [10]:
df[(df['label']=='') | (df['label'].str.strip()=='')]

Empty DataFrame
Columns: [label, review]
Index: []

In [13]:
idx = df[(df['review']=='') | (df['review'].str.strip()=='')].index

In [14]:
idx

Index([  57,   71,  147,  151,  283,  307,  313,  323,  343,  351,  427,  501,
        633,  675,  815,  851,  977, 1079, 1299, 1455, 1493, 1525, 1531, 1763,
       1851, 1905, 1993],
      dtype='int64')

In [15]:
df['label'].value_counts()

label
neg    1000
pos    1000
Name: count, dtype: int64

In [16]:
df.drop(idx, inplace=True)

In [17]:
df['label'].value_counts()

label
pos    987
neg    986
Name: count, dtype: int64

In [18]:
df.dropna(inplace=True)

In [19]:
df['label'].value_counts()

label
neg    969
pos    969
Name: count, dtype: int64

In [20]:
df.isnull().sum()

label     0
review    0
dtype: int64

In [21]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [22]:
sid = SentimentIntensityAnalyzer()

In [24]:
df['scores'] = df['review'].apply(lambda review : sid.polarity_scores(review))

In [26]:
df['compound'] = df['scores'].apply(lambda d:d['compound'])

In [29]:
df['comp_score'] = df['compound'].apply(lambda score:'pos' if score>=0 else 'neg')

In [30]:
df.head()

,label,review,scores,compound,comp_score
0,neg,how do films like mouse hunt get into theatres...,"{'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'co...",-0.9125,neg
1,neg,some talented actresses are blessed with a dem...,"{'neg': 0.12, 'neu': 0.775, 'pos': 0.105, 'com...",-0.8618,neg
2,pos,this has been an extraordinary year for austra...,"{'neg': 0.068, 'neu': 0.781, 'pos': 0.15, 'com...",0.9951,pos
3,pos,according to hollywood movies made in last few...,"{'neg': 0.071, 'neu': 0.782, 'pos': 0.147, 'co...",0.9972,pos
4,neg,my first press screening of 1998 and already i...,"{'neg': 0.091, 'neu': 0.817, 'pos': 0.093, 'co...",-0.2484,neg

In [31]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [32]:
accuracy_score(df['label'], df['comp_score'])

0.6357069143446853

In [34]:
print(classification_report(df['label'], df['comp_score']))

              precision    recall  f1-score   support

         neg       0.72      0.44      0.55       969
         pos       0.60      0.83      0.70       969

    accuracy                           0.64      1938
   macro avg       0.66      0.64      0.62      1938
weighted avg       0.66      0.64      0.62      1938

In [35]:
print(confusion_matrix(df['label'], df['comp_score']))

[[427 542]
 [164 805]]

We got 84% accuracy for this dataset using tfidf