Non negative matrix factorization is an unsupervised algorithm that simultaneously performs dimensionality reduction and clustering 

We can use it in conjuction with TF-IDF to model topics across documents

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("L:\\Workspace\\Resources\\UPDATED_NLP_COURSE\\05-Topic-Modeling\\npr.csv" , sep = "\t")

In [3]:
df.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
tf = TfidfVectorizer(max_df = 0.95 , min_df = 2, stop_words = 'english')

In [6]:
dtm = tf.fit_transform(df['Article'])

In [7]:
from sklearn.decomposition import NMF

In [8]:
nmf = NMF(n_components=6, random_state=42)

In [9]:
nmf.fit(dtm)

NMF(n_components=6, random_state=42)

In [12]:
tf.get_feature_names_out()[3000]

'ann'

In [13]:
for index, topic in enumerate(nmf.components_):
    print(f"The top 15 words for topic numner {index} : ")
    print([tf.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print('\n')

The top 15 words for topic numner 0 :
['research', 'like', 'university', 'education', 'schools', 'water', 'children', 'food', 'zika', 'study', 'percent', 'people', 'school', 'students', 'says']


The top 15 words for topic numner 1 :
['comey', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


The top 15 words for topic numner 2 :
['senate', 'house', 'act', 'people', 'tax', 'plan', 'law', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


The top 15 words for topic numner 3 :
['officers', 'syria', 'security', 'department', 'russia', 'isis', 'law', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


The top 15 words for topic numner 4 :
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


The top 15 words for topic numner 5 :
['don', 'love', 'black', 'way', 'album', 'time', 'life', 'song', 'really', 'know', 'people', 'think', 'just', 'music', 'like']

In [14]:
topic_res = nmf.transform(dtm)

In [17]:
topic_res[0].argmax()

np.int64(1)

In [18]:
df['Topic'] = topic_res.argmax(axis=1)

In [20]:
df.head(20)

                                              Article  Topic
0   In the Washington of 2016, even when the polic...      1
1     Donald Trump has used Twitter  —   his prefe...      1
2     Donald Trump is unabashedly praising Russian...      1
3   Updated at 2:50 p. m. ET, Russian President Vl...      3
4   From photography, illustration and video, to d...      3
5   I did not want to join yoga class. I hated tho...      5
6   With a   who has publicly supported the debunk...      0
7   I was standing by the airport exit, debating w...      0
8   If movies were trying to be more realistic, pe...      0
9   Eighteen years ago, on New Year’s Eve, David F...      5
10  For years now, some of the best, wildest, most...      5
11  For years now, some of the best, wildest, most...      5
12  The Colorado River is like a giant bank accoun...      0
13  For the last installment of NPR’s holiday reci...      5
14  Being overweight can raise your blood pressure...      0
15  Who’s the YouTube star of 2016? Adele singing ...      5
16  Here’s a quick roundup of some of the   you ma...      3
17  Ben Johnston doesn’t follow the rules of music...      5
18  David Bowie, Prince and George Michael are all...      5
19  In November, the typically straitlaced Office ...      1

In [21]:
topic_dict = {0:'Education', 1 : 'Politics' , 2:'Health Funds', 3:'Military', 4:'Government Country',5:'Lifestyle'}
df['Topic Label'] = df['Topic'].map(topic_dict)

In [22]:
df.head(7)

                                             Article  Topic Topic Label
0  In the Washington of 2016, even when the polic...      1    Politics
1    Donald Trump has used Twitter  —   his prefe...      1    Politics
2    Donald Trump is unabashedly praising Russian...      1    Politics
3  Updated at 2:50 p. m. ET, Russian President Vl...      3    Military
4  From photography, illustration and video, to d...      3    Military
5  I did not want to join yoga class. I hated tho...      5   Lifestyle
6  With a   who has publicly supported the debunk...      0   Education